### ISSUE TITLE
Vanilla install gives a GraphQL error

### ISSUE THREAD

**Issue by jascination** [strapi/strapi-legacy-blog#6] opened 2020-09-09 00:33 UTC
I've cloned, installed and run `develop`.

I open my browser, and I'm met with:

```
Error: {"graphQLErrors":[],"networkError":{"name":"ServerParseError","response":{},"statusCode":404,"bodyText":"<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot POST /undefined/graphql</pre>\n</body>\n</html>\n"},"message":"Network error: JSON Parse error: Unrecognized token '<'"}
```

Seems like something's broken on Strapi's end?

**Comment by EugeneLevchenya** [comment] 2020-10-06 15:38
True, have the same issue

**Comment by remidej** [comment] 2020-10-08 16:46
I'm not sure I understand the issue, I tried reproducing it but could not. Here's what I did:

* yarn install
* yarn develop
* Opened http://localhost:1337/graphql in my browser

The GraphQL playground works fine, I can make requests.

Can you give me step by step instructions to reproduce this issue?

**Comment by remidej** [comment] 2020-10-12 08:23
I'm closing this issue as long as I can't reproduce it. I'll reopen if you share more info

**Closed by remidej** 2020-10-12 08:23 UTC

**Comment by lameguest21** [comment] 2021-03-18 09:24
While defining .env file, do remove the inverted commas
So your .env file will look like this
REACT_APP_BACKEND_URL=http://localhost:8085
